### PR TITLE
CF-303 add vnd.rackspace.atomsvc+json 

### PR DESCRIPTION
**Pull request by VinnyQ**
as a known media type of the accept header, for Xml2JsonFilter to indicate that the content will be json.

### CODE REVIEW

**Comment by shintasmith** [comment]
lgtm

**Comment by shintasmith** [comment]
I will let @usnavi and @ChandraAddala also review and merge.

**Comment by usnavi** [comment]
lgtm.  @ChandraAddala can merge.

**Comment by ChandraAddala** [comment]
lgtm;

**Pull request merged**
